# Generated by Django 5.0.2 on 2024-08-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='host_layout',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='opponent_layout',
            field=models.JSONField(null=True),
        ),
    ]
