# Generated by Django 5.0.2 on 2024-08-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gameroom_host_layout_gameroom_opponent_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='host_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='opponent_ready',
            field=models.BooleanField(default=False),
        ),
    ]
