# Generated by Django 5.0.2 on 2024-08-19 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gameroom_host_ready_gameroom_opponent_ready'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='turn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turn', to=settings.AUTH_USER_MODEL),
        ),
    ]
