# Generated by Django 5.0.2 on 2024-08-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_gameroom_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='opponent_flag_in_place',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='owner_flag_in_place',
            field=models.BooleanField(default=False),
        ),
    ]
